#!/bin/bash

(echo "i<--5"; pr -s+ -m -t -l10000 $1.tim $2.tim \
 | sed "s/[A-Z].*//" | sed "s/+/ \\//" \
 | sed "s/^./cat(i<-i+1,/" | sed "s/.$/,'\\\\n')/" \
 | sed "s/^$/i<-(i+9)%\\/%5\\*5;cat('\\\\n')/") \
 | R --slave --vanilla \
 | pp -lny =900x450
