#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION WITH OPTIONAL PIPELINING
#           Shell File to Run a Series of Tests (for mat_mat)
#
# Copyright (c) 2013, 2017 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


prog=$1-test

echo " "; echo MAT_MAT

echo " "; time $prog 1000000$Z 2222 1 1

echo " "; time $prog 500000$Z 1 901 1
echo " "; time $prog 1000$Z 301 2222 1
echo " "; time $prog 1000$Z 1 2222 301

echo " "; time $prog 50000$Z 2 522 34
echo " "; time $prog 5000$Z 3 1445 62

echo " "; time $prog 2000000$Z 7 12 9
echo " "; time $prog 20000$Z 23 222 34
echo " "; time $prog 2000$Z 50 445 62

echo " "; time $prog 100000$Z 101 2 100
echo " "; time $prog 500$Z 1200 2 1299

echo " "; time $prog 20000$Z 43 72 64
echo " "; time $prog 2000$Z 100 155 112

echo " "; time $prog 10$Z 430 520 540
echo " "; time $prog 2$Z 800 1150 920
echo " "; time $prog 1$Z 1271 1341 1013

echo " "; time $prog 1$Z 1271 1341 1271
