#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION WITH OPTIONAL PIPELINING
#           Shell File to Run a Series of Tests (for sequence of operations)
#
# Copyright (c) 2013, 2017 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


prog=$1


echo " "; echo SEQUENCE

echo " "; time $prog 40000 2 2 40 381

echo " "; time $prog 20000 25 36 38 29 28
echo " "; time $prog 1000 55 145 81 93

echo " "; time $prog 30 215 201 308 270 230
echo " "; time $prog 6 487 691 570 399
echo " "; time $prog 1 1287 1201 670 499

echo " "; time $prog 2 t 1287 1201 670 499 t

echo " "; time $prog 20000 v 25 36 38 29 28
echo " "; time $prog 1000 v 55 145 81 93

echo " "; time $prog 300000 25 36 38 29 28 v
echo " "; time $prog 50000 55 145 81 93 v
