#!/bin/bash

# Run all tests, except ones involving piping or blas, and matprod-norestrict.

for i in matprod matprod-noalign matprod-alt \
         matprod-nosimd matprod-noavx; do
  echo RUNNING TESTS FOR $i
  run-tests$1 $i >& $i.out
  tim $i
done
