#!/bin/bash

# Run piped-matprod tests with helpers, splitting operations according to MINMUL

for thr in $@; do
  export HELPERS=`expr $thr - 1`
  export SPLIT=0
  export MIN=16384
  for i in piped-matprod piped-matprod-off; do
    echo RUNNING TESTS FOR $i WITH $HELPERS HELPERS, \
         SPLIT ACCORDING TO MIN OF $MIN
    ../run-tests $i >& $i-m$thr.out
    ../tim $i-m$thr
  done
done
