#!/bin/bash

# Run piped-matprod tests with helpers, splitting operations.

for thr in $@; do
  export HELPERS=`expr $thr - 1`
  export SPLIT=$thr
  echo RUNNING TESTS WITH $HELPERS HELPERS, SPLIT BY $SPLIT
  ../run-tests piped-matprod >& piped-matprod-$SPLIT.out
  ../tim piped-matprod-$SPLIT
done
