#!/bin/bash

# Run all tests, except ones involving blas.

for i in matprod matprod-aligned matprod-nosimd matprod-norestrict \
         matprod-noavx matprod-alt matprod-alt-aligned \
         piped-matprod piped-matprod-aligned piped-matprod-norestrict \
         piped-matprod-d; do
  run-tests$1 $i-test >& $i.out
  tim $i
done
