#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION WITH OPTIONAL PIPELINING
#           Shell File to Run a Series of Tests
#
# Copyright (c) 2013, 2017 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# run-tests program
#
# Uses the given test program for a variety of tests, displaying timing
# information, along with some headers.


prog=$1

echo " "; echo VEC_VEC

echo " "; time $prog 30000000 v 23 v
echo " "; time $prog 500000 v  901 v
echo " "; time $prog 50000 v 12345 v
echo " "; time $prog 5000 v 123456 v
echo " "; time $prog 500 v 1234567 v

echo " "; echo MAT_VEC

echo " "; time $prog 200000 2 2222 v
echo " "; time $prog 50000 2 12345 v

echo " "; time $prog 200000 3 2222 v
echo " "; time $prog 50000 3 10345 v

echo " "; time $prog 10000000 13 12 v
echo " "; time $prog 4000000 30 21 v
echo " "; time $prog 20000 400 400 v
echo " "; time $prog 4000 301 2222 v
echo " "; time $prog 400 280 12345 v

echo " "; echo VEC_MAT

echo " "; time $prog 10000000 v 12 13
echo " "; time $prog 4000000 v 21 30
echo " "; time $prog 20000 400 400 v
echo " "; time $prog 4000 v 2222 301
echo " "; time $prog 400 v 12345 280

echo " "; echo VEC VIA GENERAL

echo " "; time $prog 500000 1 901 1
echo " "; time $prog 4000 301 2222 1
echo " "; time $prog 4000 1 2222 301

echo " "; echo GENERAL

echo " "; time $prog 50000 2 522 34
echo " "; time $prog 5000 3 1445 62

echo " "; time $prog 2000000 7 12 9
echo " "; time $prog 20000 23 222 34
echo " "; time $prog 2000 50 445 62

echo " "; time $prog 20000 43 72 64
echo " "; time $prog 2000 100 155 112

echo " "; time $prog 10 430 520 540
echo " "; time $prog 2 800 1150 920
echo " "; time $prog 1 1271 1341 1013

echo " "; time $prog 1 1271 1341 1271

echo " "; echo OUTER

echo " "; time $prog 10000 230 1 341
echo " "; time $prog 100 2031 1 3201

echo " "; echo TRANS1

echo " "; time $prog 50000 t 2 522 34
echo " "; time $prog 5000 t 3 1445 62

echo " "; time $prog 2000000 t 7 12 9
echo " "; time $prog 20000 t 23 222 34
echo " "; time $prog 2000 t 50 445 62

echo " "; time $prog 20000 t 43 72 64
echo " "; time $prog 2000 t 100 155 112

echo " "; time $prog 10 t 430 520 540
echo " "; time $prog 2 t 800 1150 920
echo " "; time $prog 1 t 1271 1341 1013

echo " "; time $prog 1 t 1271 1341 1271
echo " "; time $prog 1 T 1271 1341 1271

echo " "; echo TRANS2

echo " "; time $prog 50000 2 522 34 t
echo " "; time $prog 5000 3 1445 62 t

echo " "; time $prog 2000000 7 12 9 t
echo " "; time $prog 20000 23 222 34 t
echo " "; time $prog 2000 50 445 62 t

echo " "; time $prog 20000 43 72 64 t
echo " "; time $prog 2000 100 155 112 t

echo " "; time $prog 10 430 520 540 t
echo " "; time $prog 3 800 1150 920 t
echo " "; time $prog 1 1271 1341 1013 t

echo " "; time $prog 1 1271 1341 1271 t
echo " "; time $prog 1 1271 1341 1271 T

echo " "; echo SEQUENCE

echo " "; time $prog 40000 2 2 40 381

echo " "; time $prog 20000 25 36 38 29 28
echo " "; time $prog 1000 55 145 81 93

echo " "; time $prog 30 215 201 308 270 230
echo " "; time $prog 6 487 691 570 399
echo " "; time $prog 1 1287 1201 670 499

echo " "; time $prog 2 t 1287 1201 670 499 t

echo " "; time $prog 20000 v 25 36 38 29 28
echo " "; time $prog 1000 v 55 145 81 93

echo " "; time $prog 300000 25 36 38 29 28 v
echo " "; time $prog 50000 55 145 81 93 v
