#!/bin/bash

# Run piped-matprod tests with helpers.

for hlp in $@; do
  export HELPERS=$hlp
  export SPLIT=`expr $hlp + 1`
  echo RUNNING TESTS WITH $HELPERS HELPERS, SPLIT BY $SPLIT
  ../run-tests piped-matprod >& piped-matprod-$HELPERS.out
  ../tim piped-matprod-$HELPERS
done
