#!/bin/bash

# Run piped-matprod tests with helpers, but not splitting operations.

for hlp in $@; do
  export HELPERS=$hlp
  unset SPLIT
  for i in piped-matprod piped-matprod-off; do
    echo RUNNING TESTS FOR $i WITH $HELPERS HELPERS, NOT SPLIT
    ../run-tests $i >& $i-hlp$HELPERS.out
    ../tim $i-hlp$HELPERS
  done
done
