#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION WITH OPTIONAL PIPELINING
#           Shell File to Run a Series of Tests (for mat_vec)
#
# Copyright (c) 2013, 2017 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


prog=$1

echo " "; echo MAT_VEC

echo " "; time $prog 1000000 2222 1 v

echo " "; time $prog 200000 2 2222 v
echo " "; time $prog 50000 2 12345 v

echo " "; time $prog 200000 3 2222 v
echo " "; time $prog 50000 3 10345 v

echo " "; time $prog 10000000 13 12 v
echo " "; time $prog 4000000 30 21 v
echo " "; time $prog 20000 400 400 v
echo " "; time $prog 4000 301 2222 v
echo " "; time $prog 400 280 12345 v
