#!/bin/bash
#
# MATPROD - A LIBRARY FOR MATRIX MULTIPLICATION WITH OPTIONAL PIPELINING
#           Shell File to Run a Series of Tests (for vec_mat)
#
# Copyright (c) 2013, 2017 Radford M. Neal.
# 
#   The matprod library is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


prog=$1

echo " "; echo VEC_MAT

echo " "; time $prog 1000000 v 1 2222

echo " "; time $prog 200000 v 2222 2
echo " "; time $prog 50000 v 12345 2

echo " "; time $prog 200000 v 2222 3
echo " "; time $prog 50000 v 10345 3

echo " "; time $prog 10000000 v 12 13
echo " "; time $prog 4000000 v 21 30
echo " "; time $prog 20000 v 400 400
echo " "; time $prog 4000 v 2222 301
echo " "; time $prog 400 v 12345 280
