#!/bin/bash

# Run all matprod tests, except matprod-norestrict.

for i in matprod matprod-off \
         matprod-noalign matprod-off-noalign \
         matprod-nosimd matprod-off-nosimd \
         matprod-noavx matprod-off-noavx \
         matprod-noalign-nosimd matprod-off-noalign-nosimd; do
  echo RUNNING TESTS FOR $i
  ../run-tests $i >& $i.out
  ../tim $i
done
