#!/bin/bash

# Run all tests, except ones involving piping or blas.

for i in matprod matprod-noalign matprod-alt \
         matprod-nosimd matprod-norestrict matprod-noavx \
         matprod-generic matprod-generic-avx matprod-generic-avx2 \
         matprod-generic-nosimd matprod-generic-nosimd2; do
  echo RUNNING TESTS FOR $i
  run-tests$1 $i-test >& $i.out
  tim $i
done
