#!/bin/bash

# tim prefix ...
#
# Creates prefix.tim from prefix.out by extracting elapased time information,
# plus headers.

for i in $@; do
  grep "^[a-zA-Z]" $i.out | fgrep -v "user" | fgrep -v "sys"| fgrep -v "Check" \
    | sed "s/real *//" | sed "s/0m//" | sed "s/s//" >$i.tim
done
